### ISSUE TITLE
QWT_NO_SVG instead of NO_QWT_SVG

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [MehdiChinoune/qwt#3]
QWT_NO_SVG instead of NO_QWT_SVG in https://github.com/MehdiChinoune/qwt/blob/b567002e8ca2719aac666f2813652c8520b6a95a/src/CMakeLists.txt#L333

**Comment by MehdiChinoune** [comment]
Thanks for reporting.

Fixed.
